name = "GivensBoson"
uuid = "13133e6c-7787-440b-86dd-4b1178ab9020"
authors = ["Qi Yang <qiyang@mail.ustc.edu.cn> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
