name = "GivensBoson"
uuid = "13133e6c-7787-440b-86dd-4b1178ab9020"
authors = ["Qi Yang <qiyang@mail.ustc.edu.cn> and contributors"]
version = "1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
